### ISSUE TITLE
Missing `owl:onProperty` in `http://edamontology.org/format_4015` 

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edamontology#705]
When converting the dev version of the ontology from owl to json with edam2json I get an error for term `http://edamontology.org/format_4015` It has restriction but the `owl:onProperty` is missing following the logs.

```log
2021-05-27T14:45:15.4434823Z ERROR:root:Error when creating node http://edamontology.org/format_4015
2021-05-27T14:45:15.4437477Z Traceback (most recent call last):
2021-05-27T14:45:15.4439040Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/bin/edam2json", line 33, in <module>
2021-05-27T14:45:15.4440472Z     sys.exit(load_entry_point('edam2json===dev', 'console_scripts', 'edam2json')())
2021-05-27T14:45:15.4441680Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/edam2json/__main__.py", line 145, in main
2021-05-27T14:45:15.4442384Z     args.func(args)
2021-05-27T14:45:15.4443451Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/edam2json/__main__.py", line 112, in print_biotools
2021-05-27T14:45:15.4444675Z     biotools_node['children'].append(process_node(subroot_node, json_ld, args.extended))
(...)
2021-05-27T14:45:15.4467911Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/edam2json/__main__.py", line 39, in process_node
2021-05-27T14:45:15.4468717Z     raise e
2021-05-27T14:45:15.4469998Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/edam2json/__main__.py", line 36, in process_node
2021-05-27T14:45:15.4470913Z     biotools_node = process_node_itself(node, json_ld, extended)
2021-05-27T14:45:15.4472142Z   File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/edam2json/__main__.py", line 74, in process_node_itself
2021-05-27T14:45:15.4473449Z     property_name = term['owl:onProperty']['@id'].replace('http://edamontology.org/','')
2021-05-27T14:45:15.4474445Z KeyError: 'owl:onProperty'
```

I am also proposing a CI action that convert the file into json to check if conversion is error-less with #704

**Comment by bryan-brancotte** [comment]
#706 fixed for format_3475 but not for format_4015

**Comment by bryan-brancotte** [comment]
You can check if there are other not missing with https://github.com/edamontology/edamontology/pull/704/checks
